### ISSUE TITLE
Python API does not work with next-gen Intel compiler

### ISSUE THREAD

**Issue by chuckyount** [intel/yask#247]
make -j all YK_CXXOPT=-O1 ranks=4 EXTRA_YK_CXXFLAGS='-qnextgen -fno-color-diagnostics'
...
*** Running the Python YASK kernel API test...
env PYTHONPATH=:/nfs/pdx/home/cyount/dev/github/yask-develop/lib:/nfs/pdx/home/cyount/dev/github/yask-develop/yask:/nfs/pdx/home/cyount/dev/github/yask-develop/yask:/nfs/pdx/home/cyount/dev/github/opesci-devito:/nfs/pdx/home/cyount/dev/github/opesci-yask:/nfs/pdx/home/cyount/dev/github/opesci-yask/yask:/nfs/pdx/home/cyount/dev/github/opesci-yask/lib python /nfs/pdx/home/cyount/dev/github/yask-develop/src/kernel/tests/yask_kernel_api_test.py
Traceback (most recent call last):
  File "/nfs/pdx/home/cyount/dev/github/yask-develop/src/kernel/tests/yask_kernel_api_test.py", line 31, in <module>
    import yask_kernel as yk
  File "/nfs/pdx/home/cyount/dev/github/yask-develop/yask/yask_kernel.py", line 15, in <module>
    from _yask_kernel import *
ImportError: /nfs/pdx/home/cyount/dev/github/yask-develop/yask/_yask_kernel.so: undefined symbol: __cxa_pure_virtual

**Comment by chuckyount** [comment]
Fixed in latest version of next-gen Intel compiler, which is now invoked as icpx instead of using the -qnextgen option.
